name = "AtomicLocks"
uuid = "de46ae7c-df16-46d9-ba75-55d31af5ce86"
authors = ["Martin Heida"]
version = "0.1"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
